use core::ops::{BitAnd, BitAndAssign, BitOr, BitOrAssign};

/// Platform-independent modifier flags attached to a normalized key event.
///
/// Unknown bits are retained so a newer frontend can communicate with an older
/// broker without silently changing the event.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
#[repr(transparent)]
pub struct KeyModifiers(u32);

impl KeyModifiers {
    /// No modifier keys are active.
    pub const NONE: Self = Self(0);
    /// Either Shift key is active.
    pub const SHIFT: Self = Self(1 << 0);
    /// Either Control key is active.
    pub const CONTROL: Self = Self(1 << 1);
    /// Either Alt/Option key is active.
    pub const ALT: Self = Self(1 << 2);
    /// The platform command/super key is active.
    pub const SUPER: Self = Self(1 << 3);
    /// Caps Lock is active.
    pub const CAPS_LOCK: Self = Self(1 << 4);

    /// Constructs a modifier set while preserving unknown bits.
    #[must_use]
    pub const fn from_bits(bits: u32) -> Self {
        Self(bits)
    }

    /// Returns the wire-format bit representation.
    #[must_use]
    pub const fn bits(self) -> u32 {
        self.0
    }

    /// Returns `true` when every flag in `other` is present.
    #[must_use]
    pub const fn contains(self, other: Self) -> bool {
        (self.0 & other.0) == other.0
    }

    /// Returns `true` when at least one flag in `other` is present.
    #[must_use]
    pub const fn intersects(self, other: Self) -> bool {
        (self.0 & other.0) != 0
    }

    /// Returns `true` when no modifier flags are present.
    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
}

impl BitOr for KeyModifiers {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

impl BitOrAssign for KeyModifiers {
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 |= rhs.0;
    }
}

impl BitAnd for KeyModifiers {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self::Output {
        Self(self.0 & rhs.0)
    }
}

impl BitAndAssign for KeyModifiers {
    fn bitand_assign(&mut self, rhs: Self) {
        self.0 &= rhs.0;
    }
}

/// Whether a normalized key was pressed or released.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum KeyState {
    /// Key-down transition.
    Pressed,
    /// Key-up transition.
    Released,
}

/// A platform-neutral, normalized keyboard event.
///
/// `keycode` is Mo's normalized logical key symbol, not a Windows virtual-key
/// code. `text` is the Unicode scalar produced by the platform layout when one
/// exists. Keeping both prevents platform key constants from leaking into the
/// engine while preserving non-text keys.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct KeyEvent {
    /// Normalized logical key symbol.
    pub keycode: u32,
    /// Active modifier flags.
    pub modifiers: KeyModifiers,
    /// Press or release transition.
    pub state: KeyState,
    /// Unicode scalar produced by the active keyboard layout, if any.
    pub text: Option<char>,
    /// Whether this event is an auto-repeat generated by the platform.
    pub repeat: bool,
}

impl KeyEvent {
    /// Constructs a normalized key event.
    #[must_use]
    pub const fn new(
        keycode: u32,
        modifiers: KeyModifiers,
        state: KeyState,
        text: Option<char>,
        repeat: bool,
    ) -> Self {
        Self {
            keycode,
            modifiers,
            state,
            text,
            repeat,
        }
    }

    /// Constructs a key-down event without translated text.
    #[must_use]
    pub const fn pressed(keycode: u32) -> Self {
        Self::new(keycode, KeyModifiers::NONE, KeyState::Pressed, None, false)
    }

    /// Constructs a key-up event without translated text.
    #[must_use]
    pub const fn released(keycode: u32) -> Self {
        Self::new(keycode, KeyModifiers::NONE, KeyState::Released, None, false)
    }

    /// Constructs a key-down event for a Unicode scalar.
    #[must_use]
    pub const fn text(character: char) -> Self {
        Self::new(
            character as u32,
            KeyModifiers::NONE,
            KeyState::Pressed,
            Some(character),
            false,
        )
    }

    /// Returns this event with the supplied modifiers.
    #[must_use]
    pub const fn with_modifiers(mut self, modifiers: KeyModifiers) -> Self {
        self.modifiers = modifiers;
        self
    }

    /// Returns this event marked as an auto-repeat event.
    #[must_use]
    pub const fn repeated(mut self) -> Self {
        self.repeat = true;
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn modifier_bits_round_trip_without_discarding_unknown_flags() {
        let unknown = 1 << 31;
        let modifiers =
            KeyModifiers::SHIFT | KeyModifiers::CONTROL | KeyModifiers::from_bits(unknown);

        assert!(modifiers.contains(KeyModifiers::SHIFT | KeyModifiers::CONTROL));
        assert!(modifiers.intersects(KeyModifiers::CONTROL | KeyModifiers::ALT));
        assert_eq!(modifiers.bits(), 0b11 | unknown);
    }

    #[test]
    fn text_event_has_stable_normalized_defaults() {
        let event = KeyEvent::text('墨').repeated();

        assert_eq!(event.keycode, '墨' as u32);
        assert_eq!(event.text, Some('墨'));
        assert_eq!(event.state, KeyState::Pressed);
        assert!(event.repeat);
        assert!(event.modifiers.is_empty());
    }
}
