[package]
name = "mo-broker"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[features]
latency-trace = []

[dependencies]
mo-domain = { path = "../mo-domain" }
mo-engine = { path = "../mo-engine" }
mo-ipc = { path = "../mo-ipc" }

[target.'cfg(windows)'.dependencies]
mo-rime = { path = "../mo-rime" }
mo-windows-pipe = { path = "../mo-windows-pipe" }
mo-windows-platform = { path = "../mo-windows-platform" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "mo-broker-tcp-spike"
path = "src/main.rs"

[[bin]]
name = "mo-broker"
path = "src/named_pipe_main.rs"

[lints.rust]
unsafe_code = "forbid"
